networks:
  app:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
      - './.htpasswd:/etc/nginx/.htpasswd'
    depends_on:
      - backend
      - frontend
    networks:
      - app

  backend:
    build: ./backend
    environment:
      - LM_STUDIO_HOST=host.docker.internal
      - LM_STUDIO_PORT=2122
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    networks:
      - app

  frontend:
    build: ./frontend
    networks:
      - app